#pragma once

#define VIAL_ENCODER_DEFAULT { KC_VOLD, KC_VOLU, RGB_VAD, RGB_VAI, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS }
#define VIA_CUSTOM_LIGHTING_ENABLE
#define VIA_QMK_RGBLIGHT_ENABLE
#define PREVENT_STUCK_MODIFIERS
#define FORCE_NKRO
